import TablesOfContents from "../TableOfContents";

function DocsJwt() {
  const sections = [
    { id: "secret-key", label: "Secret Key" },
    { id: "token-expiry", label: "Token Expiry" },
    { id: "token-storage", label: "Token Storage" },
    { id: "cookie-name", label: "Cookie Name" },
    { id: "jwt-algorithm", label: "JWT Algorithm" },
  ];

  return (
    <div className="max-w-6xl mx-auto flex flex-col xl:flex-row gap-8 xl:gap-16">
      {/* Main Content */}
      <div className="flex-1 min-w-0 xl:pr-6 text-zinc-300">
        {/* Secret Key */}
        <section id="secret-key" className="mb-8">
          <h2 className="text-xl font-semibold text-white mb-2">Secret Key</h2>

          <p className="text-zinc-400 leading-8 mb-2">
            The Secret Key is used to sign and verify JWT tokens. Every token
            generated by your application relies on this key for validation.
          </p>

          <div className="rounded-md border border-amber-500/20 bg-amber-500/5 p-4">
            <h3 className="text-amber-300 font-medium mb-2">Important</h3>

            <p className="text-zinc-400 leading-7">
              Save your Secret Key before leaving this page. Bouncer does not
              display previously generated Secret Keys for security reasons.
            </p>
          </div>
        </section>

        {/* Token Expiry */}
        <section id="token-expiry" className="mb-8">
          <h2 className="text-xl font-semibold text-white mb-2">
            Token Expiry
          </h2>

          <p className="text-zinc-400 leading-8 mb-2">
            Configure how long JWT tokens remain valid before users must
            authenticate again.
          </p>

          <div className="flex flex-wrap gap-3 mb-2">
            <span className="px-4 py-2 rounded-full border border-zinc-800 text-sm">
              Minutes
            </span>

            <span className="px-4 py-2 rounded-full border border-zinc-800 text-sm">
              Hours
            </span>

            <span className="px-4 py-2 rounded-full border border-zinc-800 text-sm">
              Days
            </span>
          </div>

          <p className="text-zinc-400 leading-8">
            Shorter expiry durations provide stronger security, while longer
            durations reduce the frequency at which users need to log in.
          </p>
        </section>

        {/* Token Storage */}
        <section id="token-storage" className="mb-8">
          <h2 className="text-xl font-semibold text-white mb-2">
            Token Storage
          </h2>

          <p className="text-zinc-400 leading-8 mb-2">
            Choose where JWT tokens should be stored after successful
            authentication.
          </p>

          <div className="grid md:grid-cols-2 gap-5">
            <div className="rounded-xl border border-zinc-800 p-5">
              <h3 className="font-medium text-white mb-3">
                Authorization Header (Bearer)
              </h3>

              <p className="text-zinc-400 leading-7 mb-4">
                The token is stored client-side and sent with every request
                using the Authorization header.
              </p>

              <div className="rounded-lg border border-zinc-800 bg-zinc-900/30 p-3">
                <code className="text-sm text-zinc-300">
                  Authorization: Bearer JWT_TOKEN
                </code>
              </div>
            </div>

            <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-5">
              <div className="text-xs uppercase tracking-wider text-emerald-400 mb-2">
                Default & Recommended
              </div>

              <h3 className="font-medium text-white mb-3">HttpOnly Cookie</h3>

              <p className="text-zinc-400 leading-7">
                Cookies are generally safer against XSS attacks because they
                cannot be accessed through client-side JavaScript. Bouncer uses
                HttpOnly Cookies by default.
              </p>
            </div>
          </div>
        </section>

        {/* Cookie Name */}
        <section id="cookie-name" className="mb-8">
          <h2 className="text-xl font-semibold text-white mb-2">Cookie Name</h2>

          <p className="text-zinc-400 leading-8 mb-2">
            When using HttpOnly Cookies, you can customize the cookie name used
            to store JWT tokens.
          </p>

          <div className="grid md:grid-cols-2 gap-5 mb-2">
            <div className="rounded-xl border border-zinc-800 p-4">
              <div className="text-xs uppercase tracking-wider text-zinc-500 mb-2">
                Default Value
              </div>

              <code className="text-blue-400">authToken</code>
            </div>

            <div className="rounded-xl border border-zinc-800 p-4">
              <div className="text-xs uppercase tracking-wider text-zinc-500 mb-2">
                Recommended Values
              </div>

              <div className="flex flex-wrap gap-2">
                <span className="px-3 py-1 rounded-full border border-zinc-800 text-sm">
                  authToken
                </span>

                <span className="px-3 py-1 rounded-full border border-zinc-800 text-sm">
                  jwt_token
                </span>
              </div>
            </div>
          </div>

          <p className="text-zinc-400 leading-8">
            Use a clear and descriptive cookie name to simplify debugging and
            authentication management.
          </p>
        </section>

        {/* JWT Algorithm */}
        <section id="jwt-algorithm">
          <h2 className="text-xl font-semibold text-white mb-2">
            JWT Algorithm
          </h2>

          <div className="mb-2">
            <span className="inline-flex items-center rounded-full border border-zinc-800 px-3 py-1 text-sm text-zinc-400">
              Optional Setting
            </span>
          </div>

          <p className="text-zinc-400 leading-8 mb-2">
            Select the signing algorithm used to generate and verify JWT tokens.
            If no algorithm is selected, the default configuration will be used.
          </p>

          <div className="grid md:grid-cols-3 gap-4 mb-8">
            <div className="rounded-xl border border-zinc-800 p-4">
              <h3 className="font-medium text-white mb-2">HS256</h3>

              <p className="text-zinc-500 text-sm">
                Fast and widely supported.
              </p>
            </div>

            <div className="rounded-xl border border-zinc-800 p-4">
              <h3 className="font-medium text-white mb-2">HS384</h3>

              <p className="text-zinc-500 text-sm">
                Stronger hashing with additional security.
              </p>
            </div>

            <div className="rounded-xl border border-zinc-800 p-4">
              <h3 className="font-medium text-white mb-2">HS512</h3>

              <p className="text-zinc-500 text-sm">
                Highest hashing strength among supported options.
              </p>
            </div>
          </div>

          <p className="text-zinc-400 leading-8">
            For most applications, HS256 provides an excellent balance between
            performance and security.
          </p>
        </section>
      </div>

      {/* Table of Contents */}
      <TablesOfContents sections={sections} />
    </div>
  );
}

export default DocsJwt;
